baseURL: https://tunan-wang.netlify.app/
languageCode: en
theme: hugo-apero
title: Tunan's Homepage
author: Tunan Wang
copyright: 'Tunan Wang'
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 6
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/limit.jpg
  headingFontFamily: sans-serif
  logo: no
  mainSections:
    - blog
    - project
    - talk
  navallcaps: yes
  orgLocal: no
  orgName: no
  sharing_image: /img/papillons.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/Tuna22/
  socialInFooter: no
  socialInHeader: yes
  textFontFamily: sans-serif
  theme: grayscale
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: hugo-apero/hugo-apero-docs
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
  header:
    - name: Research
      title: Research experiences
      url: /Research/
      weight: 1
    - name: Teaching
      title: teach
      url: /teach/
      weight: 2
    - name: Talks
      title: Talks
      url: /talk/
      weight: 3
    - name: CV
      title: CV
      url: https://github.com/Tuna22/CV/blob/main/CV%20Tunan%20Wang.pdf
      weight: 4
    - name: Blog
      title: collection
      url: /collection/
      weight: 5
    - name: recipe
      title: recipe
      url: /recipe/
      weight: 6      
      
privacy:
  disqus:
    disable: yes
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: yes
    simple: yes
  twitter:
    disable: yes
    enableDNT: yes
    simple: no
  vimeo:
    disable: yes
    enableDNT: yes
    simple: yes
  youtube:
    disable: yes
    privacyEnhanced: yes
